version: "3"

services:
  user:
    container_name: user
    build:
      context: ./services/user
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  product:
    container_name: product
    build:
      context: ./services/product
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
