version: "3"

services:
  react-ui:
    build:
      context: ./front
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
      - ./front:/usr/src/app/front
      - /usr/src/app/front/node_modules
  user:
    container_name: user
    build:
      context: ./services/user
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
  product:
    container_name: product
    build:
      context: ./services/product
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
